base_url = "https://kafkaa.xyz/"
compile_sass = false
minify_html = true
generate_feeds = true
default_language = "en"
author = '0xkafkaa'
taxonomies = [
    {name = "tags", feed = false},
]

[languages.fr]
# weight = 2
# languageName = "Fran√ßais"
# languageCode = "fr"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "0xkafkaa"
display_author = true

favicon = "favicon.ico"
image = ""

default_theme = "dark"
list_pages = false
twitter_card = false

header_nav = [
  { url = "/", name_en = "Home", name_fr = "/accueil/" },
  { url = "/writings", name_en = "Writings", name_fr = "/blog" },
  { url = "https://github.com/0xkafkaa/kafkaa.xyz", name_en = "Code", name_fr = "/livres" },
  { url = "/atom.xml", name_en = "RSS", name_fr = "/notes" },

]
